apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: open-webui
  name: open-webui
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 8080
  selector:
    io.kompose.service: open-webui
status:
  loadBalancer: {}
