apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: open-webui
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: open-webui
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/openwebui-default: "true"
        io.kompose.service: open-webui
    spec:
      containers:
        - env:
            - name: ENABLE_OLLAMA_API
              value: "false"
            - name: OPENAI_API_BASE_URL
              value: http://pipelines:9099
            - name: OPENAI_API_KEY
              value: 0p3n-w3bu!
            - name: WEBUI_SECRET_KEY
          image: ghcr.io/open-webui/open-webui:main
          name: open-webui
          ports:
            - containerPort: 8080
              hostPort: 3000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui
      restartPolicy: Always
      volumes:
        - name: open-webui
          persistentVolumeClaim:
            claimName: open-webui
status: {}
